export const GET_PHIM_API = "GET_PHIM_API";
export const GET_PHIM_SAP_CHIEU_API = "GET_PHIM_SAP_CHIEU_API";
export const CHI_TIET_PHIM = "CHI_TIET_PHIM";
export const DANH_SACH_PHIM_PHAN_TRANG = "DANH_SACH_PHIM_PHAN_TRANG";
